---
title: "STA582_ANOVA"
output: html_document
---

ANOVA with R

```{r}
y1=c(29,28,23,26,26,19,25,29,26,28)
y2=c(17,25,24,19,28,21,20,25,19,24)
y3=c(17,16,21,22,23,18,20,17,25,21)
y4=c(18,20,25,24,16,20,20,17,19,17)
y=c(y1, y2, y3, y4)
fctr=rep(c(1,2,3,4), each=10)
datset=as.data.frame(cbind(y, fctr))
#######
summary(factor(fctr))
m.anova=lm(y~factor(fctr), data=datset)
summary(m.anova)

datset$fctr <- factor(datset$fctr)
m1 <- lm(y ~ fctr, data = datset)
datset <- within(datset, fctr <- relevel(datset$fctr, "3"))
m2 <- lm(y ~ fctr, data = datset)
summary(m1)
summary(m2)

anova(m.anova)
```

```{r}
plot(factor(datset$fctr), datset$y, col = "mistyrose1")
```


```{r}
piq=read.table("http://people.usm.maine.edu/cpeng/STA582/PIQ.txt", header=T)
PIQ=piq$PIQ
Brain=piq$Brain


cate.brain = ifelse(Brain<85, 1,
              ifelse(Brain<90,2,
                ifelse(Brain<100,3, 4)))
cate.brain 

id.1=which(cate.brain==1)
id.2=which(cate.brain==2)
id.3=which(cate.brain==3)
id.4=which(cate.brain==4)

plot(Brain, PIQ, main="Scatter Plot between PIQ and Brain Size") 
points(Brain[id.1], PIQ[id.1],col=1, pch="1")
points(Brain[id.2], PIQ[id.2],col=2, pch="2")
points(Brain[id.3], PIQ[id.3],col=3, pch="3")
points(Brain[id.4], PIQ[id.4],col=4, pch="4")
```

