---
title: "STA582 Linear Regression"
output: html_document
---

Does a person's IQ depend on their brain size, height and weight?

Load the data:

```{r}
piq=read.table("http://people.usm.maine.edu/cpeng/STA582/PIQ.txt", header=T)
```


Explore pairwise relationships:

```{r}
# Helper functions
panel.cor <- function(x, y, digits = 2, prefix = "", cex.cor, ...)
{
  usr <- par("usr"); on.exit(par(usr))
  par(usr = c(0, 1, 0, 1))
  r <- abs(cor(x, y))
  txt <- format(c(r, 0.123456789), digits = digits)[1]
  txt <- paste0(prefix, txt)
  if(missing(cex.cor)) cex.cor <- 0.8/strwidth(txt)
  text(0.5, 0.5, txt, cex = 2)
}
panel.hist <- function(x, ...)
{
  usr <- par("usr"); on.exit(par(usr))
  par(usr = c(usr[1:2], 0, 1.5) )
  h <- hist(x, plot = FALSE)
  breaks <- h$breaks; nB <- length(breaks)
  y <- h$counts; y <- y/max(y)
  rect(breaks[-nB], 0, breaks[-1], y, col = "cyan", ...)
}

# Create pairwise scatter plots
pairs(piq, diag.panel = panel.hist, lower.panel = panel.smooth, upper.panel = panel.cor)
```


Manual Calculation using matrix operations
```{r}
PIQ=piq$PIQ
Brain=piq$Brain
Height=piq$Height
Weight=piq$Weight
Y = PIQ
n=length(Y)
X=cbind(rep(1,n),Brain, Height)
p=3
## LSE of regression coefficients
b = solve(t(X)%*%X)%*%t(X)%*%Y
b
### Residuals
E=Y-(b[1]+b[2]*Brain+b[3]*Height)
mean(E)

MSE=as.numeric(t(E)%*%E/(n-p))
MSE
Vb=MSE*solve(t(X)%*%X)
Vb
SE=sqrt(diag(Vb))
SE

TS=b/SE
TS

pval=2*(1-pt(abs(TS),n-p))
pval

#####
Result=cbind(par=b, se=SE, T=TS, Pval=pval)
colnames(Result)=c("LSE", "se", "TS", "P(|t|>TS)")
rownames(Result)=c("Intercept", "Brain","Height")
Result
```


Using built-in function: lm()
```{r}
m0=lm(PIQ~Brain+Height)
summary(m0)
```


Model Diagnostics
```{r}
#par(mfrow=c(2,2))
plot(m0)
```






